copy_file 'lib/templates/erb/scaffold/_form.html.erb.tt'
copy_file 'lib/templates/erb/scaffold/edit.html.erb.tt'
copy_file 'lib/templates/erb/scaffold/index.html.erb.tt'
copy_file 'lib/templates/erb/scaffold/new.html.erb.tt'
copy_file 'lib/templates/erb/scaffold/show.html.erb.tt'
